name: Exemplo Artifact
run-name: Exemplo de Artifact

on:
  workflow_dispatch: 

jobs:
  upload-artifact:
    runs-on: ubuntu-latest
      steps:
        - name: Listagem de arqvuivos
          run: ls
        - name: Gerar alguns arquivos
          run: |
            mkdir artefatos
            echo "Arquivos de teste 01" > ./artefatos/primeiro_arquivo.txt"
            echo "Arquivos de teste 02" > ./artefatos/segundo_arquivo.txt"
            echo "Arquivos de teste 03" > ./artefatos/terceiro_arquivo.txt"
            echo "Arquivos de teste 04" > ./artefatos/quarto_arquivo.txt"
            echo "Arquivos de teste 05" > ./artefatos/quinto_arquivo.txt"
